version: 1.0.{build}

environment:
  matrix:
  - python: 27
  - python: 35
  - python: 35-x64
  - python: 36
  - python: 36-x64

install:
  - cmd: >-
      SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%
      python -m pip install -U pip wheel setuptools
      pip install -r requirements.txt

build_script:
  - cmd: >-
      python -u setup.py clean
      python -u setup.py bdist_wheel --static-deps

test_script:
  - ps: Get-ChildItem dist\*.whl | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
